### PR TITLE
Tuple sort test

### PR DESCRIPTION
**Pull request by JBlond**

### CODE REVIEW

**Review by DigiLive — APPROVED** [review]
I'm not sure these tests will cover the complete function. You can check it with PHPUnit code coverage.

**Comment by JBlond** [comment]
Well, it doesn't cover all the code.
coverage

I wonder how to do that. The lines 31+32 seem to be the same as the lines 43+44

**Comment by DigiLive** [comment]
Lines 31 and 32, 35 and 36 count length of the array elements.

Lines 40 and 41, 43 and 44 count the amount of the array elements.

Add a test to sort 2 arrays with a different element count.

**Comment by DigiLive** [comment]
I did some investigation and there's no need for vacation yet.

For `DiffUtils::tupleSort()` to function properly, the sizes of `$aArray` and `$bArray` should be the same.
This means line 41 can't be reached without a warning or fatal error.

Since the elements of `$matchingBlocks` all have the same length, we've never encountered this warning/error before.
But this means again line 41 can't be reached because of the comparison at line 38.

The function will return a value as latest at line 39.

We should investigate how `DiffUtils::tupleSort()` actually sorts `$matchingBlocks`, because I don't see any difference between
```php
usort(
    $matchingBlocks,
    function ($aArray, $bArray) {
        return tupleSort($aArray, $bArray);
    }
);
```
and `sort($matchingBlocks);` and `array_multisort($matchingBlocks);`.

**Comment by DigiLive** [comment]
We can rule out `array_multisort()`. Its purpose is to sort multiple arrays at once or elements of a multi-dimensional array.

I think we're good to go with `sort($matchingBlocks);`, but wth did someone implemented `usort()` with the `tupleSort()` callback??

**Comment by JBlond** [comment]
> but wth did someone implemented usort() with the tupleSort() callback??


 In the [python difflib](https://github.com/python/cpython/blob/3.10/Lib/difflib.py#L464) where this comes from, it uses a simple `sort`. The unit tests and the example still work fine with `sort()`.I think we should ax it. Or simplify it using the new `<=>` Spaceship operator

**Comment by JBlond** [comment]
> but wth did someone implemented usort() with the tupleSort() callback??
this was done in the very first commit from Chris Boulton.

**Comment by DigiLive** [comment]
Yeah... I've checked Chris's repo also and noticed it's the same quirky callback function.

I think the sort function is sufficient.
Then there's no need for a callback.

We can leave the function in the DiffUtils class to revert the sorting i.c.o. unexpected results in the future and remove it once we're confident in the updated sort function.

**Review by DigiLive — APPROVED** [review]

**Pull request merged**
