### PR TITLE
Add Console support

### PR DESCRIPTION
**Pull request by JBlond**

### CODE REVIEW

**Comment by DigiLive** [comment]
Either I'm late with reviewing or you're early with merging 😅.
Anyway... Looks promising so far. No real problems detected.
Let me know if you need assistance. I recall you mentioning to indicate inline changes?

**Comment by JBlond** [comment]
Yepp. but that would require to the the html based class and use background color.

**Comment by DigiLive** [comment]
Just to avoid us both working on the same...
Would you like me to take an attempt for unified cli output with inline colors?

**Comment by JBlond** [comment]
Yes, that would be great

**Pull request merged**
